# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-19 05:50
from __future__ import unicode_literals

import common.util.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30000)),
                ('SubTitle', models.CharField(max_length=200)),
                ('Subject', models.TextField(default='')),
                ('picture', models.ImageField(blank=True, upload_to=common.util.utils.user_path)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
